---
title: "2025-Final Project"
output: html_document
date: "2025-03-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(knitr)
df <- data.frame(
  Group= c("BNT162b2", "Placebo", "Total"),
  Infected= c(8, 162, 170),
  Uninfected=c(17403,17349,34752),
  Sample_size= c(17411, 17511, 34922)
)
kable(df, caption = "Vaccine Efficacy in Trails ")

```

```{r}
17411-8
17511-162
34922-170
```

```{r}
library(ggplot2)
df$InfectionRate <- 100 * df$Infected / df$Sample_size
df
df_no_total <- subset(df, Group != "Total")
ggplot(df_no_total, aes(x = Group, y = InfectionRate)) +
  geom_bar(stat = "identity", fill = "steelblue", width = 0.4) +
  geom_text(aes(label = paste0(round(InfectionRate, 5), "%")), 
            vjust = -0.5, 
            size = 4) +
  labs(
    title = "Infection Rate by Group",
    x = "Group",
    y = "Infection Rate (%)"
  ) +
  theme_minimal()

```

```{r}
groups <- c("BNT162b2", "Placebo")
infected <- c(8, 162)
pie(
  x = infected,
  labels = groups,
  main = "Infected Cases by Group"
)
```

